import {
  Button,
  NavBar,
  Cell,
  CellGroup,
  Empty,
  Icon,
  Tabbar,
  TabbarItem,
  Form,
  Field,
  Popup,
  Dialog,
  Toast,
  Loading,
  PullRefresh,
  List,
  Image as VanImage,
  Swipe,
  SwipeItem,
  Lazyload,
  Tab,
  Tabs,
  Search,
  DropdownMenu,
  DropdownItem,
  Grid,
  GridItem,
  Tag,
  Checkbox,
  CheckboxGroup,
  Radio,
  RadioGroup,
  Switch,
  Stepper,
  Rate,
  Uploader,
  DatetimePicker,
  Calendar,
  Picker,
  Area,
  AddressEdit,
  AddressList,
  ContactCard,
  ContactList,
  ContactEdit,
  CouponList,
  CouponCell,
  SubmitBar,
  Card,
  Sidebar,
  SidebarItem,
  NoticeBar,
  Progress,
  Circle,
  Divider,
  Sticky,
  Collapse,
  CollapseItem,
  CountDown,
  ShareSheet,
  TreeSelect,
  IndexBar,
  IndexAnchor,
  NavBar as VanNavBar,
  Tab as VanTab,
  Tabs as VanTabs,
  ImagePreview,
  Overlay,
  Popover,
  ActionSheet,
  Notify,
  SwipeCell,
  Slider,
  Steps,
  Step,
  Pagination,
  Badge,
  Cell as VanCell,
  CellGroup as VanCellGroup,
  Icon as VanIcon,
  Loading as VanLoading,
  PullRefresh as VanPullRefresh,
  List as VanList,
  Swipe as VanSwipe,
  SwipeItem as VanSwipeItem,
  Lazyload as VanLazyload,
  Search as VanSearch,
  DropdownMenu as VanDropdownMenu,
  DropdownItem as VanDropdownItem,
  Grid as VanGrid,
  GridItem as VanGridItem,
  Tag as VanTag,
  Checkbox as VanCheckbox,
  CheckboxGroup as VanCheckboxGroup,
  Radio as VanRadio,
  RadioGroup as VanRadioGroup,
  Switch as VanSwitch,
  Stepper as VanStepper,
  Rate as VanRate,
  Uploader as VanUploader,
  DatetimePicker as VanDatetimePicker,
  Calendar as VanCalendar,
  Picker as VanPicker,
  Area as VanArea,
  AddressEdit as VanAddressEdit,
  AddressList as VanAddressList,
  ContactCard as VanContactCard,
  ContactList as VanContactList,
  ContactEdit as VanContactEdit,
  CouponList as VanCouponList,
  CouponCell as VanCouponCell,
  SubmitBar as VanSubmitBar,
  Card as VanCard,
  Sidebar as VanSidebar,
  SidebarItem as VanSidebarItem,
  NoticeBar as VanNoticeBar,
  Progress as VanProgress,
  Circle as VanCircle,
  Divider as VanDivider,
  Sticky as VanSticky,
  Collapse as VanCollapse,
  CollapseItem as VanCollapseItem,
  CountDown as VanCountDown,
  ShareSheet as VanShareSheet,
  TreeSelect as VanTreeSelect,
  Skeleton as VanSkeleton,
  IndexBar as VanIndexBar,
  IndexAnchor as VanIndexAnchor,
  ImagePreview as VanImagePreview,
  Overlay as VanOverlay,
  Popover as VanPopover,
  ActionSheet as VanActionSheet,
  Notify as VanNotify,
  SwipeCell as VanSwipeCell,
  Slider as VanSlider,
  Steps as VanSteps,
  Step as VanStep,
  Pagination as VanPagination,
  Badge as VanBadge,
} from 'vant'

// 导入样式
import 'vant/lib/index.css'

// 导出所有组件
export {
  Button,
  NavBar,
  Cell,
  CellGroup,
  Empty,
  Icon,
  Tabbar,
  TabbarItem,
  Form,
  Field,
  Popup,
  Dialog,
  Toast,
  Loading,
  PullRefresh,
  List,
  VanImage,
  Swipe,
  SwipeItem,
  Lazyload,
  Tab,
  Tabs,
  Search,
  DropdownMenu,
  DropdownItem,
  Grid,
  GridItem,
  Tag,
  Checkbox,
  CheckboxGroup,
  Radio,
  RadioGroup,
  Switch,
  Stepper,
  Rate,
  Uploader,
  DatetimePicker,
  Calendar,
  Picker,
  Area,
  AddressEdit,
  AddressList,
  ContactCard,
  ContactList,
  ContactEdit,
  CouponList,
  CouponCell,
  SubmitBar,
  Card,
  Sidebar,
  SidebarItem,
  NoticeBar,
  Progress,
  Circle,
  Divider,
  Sticky,
  Collapse,
  CollapseItem,
  CountDown,
  ShareSheet,
  TreeSelect,
  IndexBar,
  IndexAnchor,
  VanNavBar,
  VanTab,
  VanTabs,
  ImagePreview,
  Overlay,
  Popover,
  ActionSheet,
  Notify,
  SwipeCell,
  Slider,
  Steps,
  Step,
  Pagination,
  Badge,
  BadgeGroup,
  VanCell,
  VanCellGroup,
  VanIcon,
  VanLoading,
  VanPullRefresh,
  VanList,
  VanSwipe,
  VanSwipeItem,
  VanLazyload,
  VanSearch,
  VanDropdownMenu,
  VanDropdownItem,
  VanGrid,
  VanGridItem,
  VanTag,
  VanCheckbox,
  VanCheckboxGroup,
  VanRadio,
  VanRadioGroup,
  VanSwitch,
  VanStepper,
  VanRate,
  VanUploader,
  VanDatetimePicker,
  VanCalendar,
  VanPicker,
  VanArea,
  VanAddressEdit,
  VanAddressList,
  VanContactCard,
  VanContactList,
  VanContactEdit,
  VanCouponList,
  VanCouponCell,
  VanSubmitBar,
  VanCard,
  VanSidebar,
  VanSidebarItem,
  VanNoticeBar,
  VanProgress,
  VanCircle,
  VanDivider,
  VanSticky,
  VanCollapse,
  VanCollapseItem,
  VanCountDown,
  VanShareSheet,
  VanTreeSelect,
  VanSkeleton,
  VanIndexBar,
  VanIndexAnchor,
  VanImagePreview,
  VanOverlay,
  VanPopover,
  VanActionSheet,
  VanNotify,
  VanSwipeCell,
  VanSlider,
  VanSteps,
  VanStep,
  VanPagination,
  VanBadge,
} 